services:
  postgres:
    image: postgres:16-alpine
    container_name: serialcare-postgres
    environment:
      POSTGRES_DB: serialcare_db
      POSTGRES_USER: serialcare_user
      POSTGRES_PASSWORD: serialcare_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

volumes:
  postgres_data:
